config/routes.rb
Smsflow::Application.routes.draw do


  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup' }
  namespace :user do
    root :to => 'messages#index'
  end
  resources :messages
  get 'credit' => 'credit#index', :as => 'credit'
  mount Resque::Server.new, :at => '/queues'
  mount Api::V1::App.new, :at => '/api/v1/services'
  root :to => 'pages#index'
end

app/models/message.rb
class Message

  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id, :type => Integer
  field :recipients, :type => Array
  field :body
  field :sent, :type => Boolean, :default => false

  validates_presence_of :recipients
  validates_presence_of :body
  validates_length_of :body, :maximum => 140

  belongs_to :user

  after_save :send_message
  
  def recipients=(args)
    if args.is_a?(Array)
      super(args)
    elsif args.is_a?(String)
      super(args.gsub(/\s+/, '').split(','))
    else
      return nil
    end
  end

  def recipients
    self.attributes['recipients'].blank? ? nil : self.attributes['recipients'].join(', ')
  end

  private

  def send_message
    Resque.enqueue(SmsWorker, self.id)
  end
end

app/models/sms_worker.rb
class SmsWorker

  @queue = :sms

#  def self.perform(message_id)
#    message = Message.find(message_id)
#
#    sess = Patron::Session.new
#    sess.timeout = 20
#    sess.base_url = 'http://api.tropo.com'
#    sess.headers['User-Agent'] = 'smsflow/1.0'
#
#    token = '037ca9435ed55142a45b27c68cea1b608ebd61f00a8ad415281259dd0d9fc56ee102bc957'
#    recipients = CGI::escape(message.recipients.to_json)
#    message_body = CGI::escape(message.body)
#
#    resp = sess.get("/1.0/sessions?action=create&token=#{token}&mobile=#{recipients}&message=#{message_body}")
#
#    if resp.status == 200
#      message.update_attribute(:sent, true)
#      message.user.credit -= 1
#      message.user.save
#    end
#  end
end

app/models/user.rb
class User

  include Mongoid::Document
  include Mongoid::Timestamps

  field :credit, :default => '0'

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable



  validates_uniqueness_of :email

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
 
  # esto empezará a funcionar en la versión 2
  #before_filter :set_locale
  
  # para el redirect tras el login
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || messages_path
  end

  private

  def set_locale
    # Si lang nos viene desde params[]
    if params[:lang]
      I18n.locale = params[:lang]
      session[:lang] = I18n.locale
    else
      # Si el usuario tiene en la sesión la clave lang
      if session[:lang]
        I18n.locale = session[:lang]
      else
        # No nos viene nada dado, lo configuramos
        user_lang = extract_user_lang_from_accept_language_header
        supported_langs = [:es, :en]
        if supported_langs.include?(user_lang)
          I18n.locale = user_lang 
        else
          # Si no hay manera de setear lang, mostramos el idioma por defecto
          I18n.locale = :es
        end
        session[:lang] = I18n.locale
      end
    end
  end
  
  def extract_user_lang_from_accept_language_header
    if request.env['HTTP_ACCEPT_LANGUAGE']
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    end
  end
end

app/controllers/credit_controller.rb
class CreditController < ApplicationController

  before_filter :authenticate_user!

  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authenticate_user!

  def index
    @messages = current_user.messages.desc(:created_at)
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    @message.user = current_user
    if @message.save
      redirect_to(messages_url, :notice => t('message_was_successfully_sended'))
    else
      render :action => 'index'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_helper.rb
module CreditHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/credit/index.html.erb
<h1>Credit#index</h1>
<p>Find me in app/views/credit/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <title><%= @page_title %> - SMS Flow</title>
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'jquery.jslidernews.css' %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery.easing' %>
    <%= javascript_include_tag 'jquery.jslidernews' %>
    <%= csrf_meta_tag %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24446548-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
  <body>
    <div id="header">
      <div id="top-header">
        <div id="flash-messages">
          <% flash.each do |name, msg| %>
            <div id="<%= "flash-#{name}" %>">
              <%= content_tag :span, msg %>
            </div>
          <% end %>
          &nbsp;
        </div>
        <div id="accounts">
          <ul>
            <% unless user_signed_in? %>
              <li><%= link_to t(:create_account), new_user_registration_path %></li>
              <li><%= link_to t(:login), new_user_session_path %></li>
            <% else %>
              <li><%= link_to "Tienes #{current_user.credit} créditos", credit_url %></li>
              <li><%= link_to t(:logout), destroy_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div><!-- top-header -->
      <div class="clear"></div>
      <div id="logo">
        <%= link_to image_tag('logo.png'), root_path %>
      </div>
      <div id="navbar">
        <div id="main-navbar">
          <ul>
            <% if user_signed_in? %>
              <li><%= link_to t(:messages), messages_path %></li>
            <% end %>
            <li><%= link_to t(:rates), '#' %></li>
            <li><%= link_to t(:help), '#' %></li>
          </ul>
        </div>
      </div><!-- navbar -->
    </div><!-- header -->
    <div id="content">
      <%= yield %>
    </div><!-- content -->
    <div id="footer">
      <div id="footer-links">
        <ul>
          <li>Copyright &copy; <%= Time.now.year %> aLabs</li>
          <li><%= link_to t(:licensed_under_gnu_affero), 'https://github.com/alabs/smsflow/blob/master/LICENSE' %></li>
          <li><%= t(:about) %></li>
          <li><%= t(:developers) %></li>
          <li><%= t(:terms_of_use) %></li>
          <li><%= t(:privacy_policy) %></li>
        </ul>
      </div>
      <div id="powered">
        <%= link_to t(:powered_by_alabs), 'http://alabs.es/' %>
      </div>
    </div><!-- footer -->
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<% @page_title = t(:messages) %>
<div id="content-main">
  <div id="new-new-message-form">
    <h3><%= t(:send_new_message) %></h3>
    <%= form_for(@message) do |f| %>
      <div id="message-form">
        <div class="form-field message-field">
            <%= f.text_area :body, :rows => 4, :placeholder => t(:placeholder_message), :autofocus => true, :required => true %>
        </div>
      </div><!-- message-form -->
      <div id="groups-to-send-the-message-and-rate">
        <%= f.label t(:recipients) %>:<br />
        <%= f.text_area :recipients, :rows => 4, :cols => 27, :placeholder => t(:placeholder_recipients), :required => true %>
        <div id="rate">
          <label>Coste de este envio</label>:<br />
          <span>0.00 €</span>
        </div>
      </div>
      <div id="send-message-buttons">
        <div id="counter">
          0
        </div>
        <div id="submit-message-button">
          <%= f.submit t(:send) %>
        </div>
      </div>
    <% end %>
  </div><!-- new-new-message-form -->
  <div class="clear"></div>
  <div id="message-list">
    <h3><%= t(:sent_messages) %></h3>
    <% if @messages.size > 0 %>
      <table>
        <tr>
          <th id="mdestination"><%= t(:destination) %></th>
          <th id="mbody"><%= t(:message) %></th>
          <th id="mdate"><%= t(:date) %></th>
        </tr>
        <% @messages.each do |message| %>
          <tr>
            <td>
              <%= message.recipients.each {|recipient| recipient } %>
            </td>
            <td><%= message.body %></td>
            <td><%= message.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <h3><%= t(:you_dont_send_any_messages_yet) %></h3>
    <% end %>
  </div>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/pages/index.html.erb
<% @page_title = 'Inicio' %> 

<!-- SLIDESHOW INICIO --> 
<div id="lofslidecontent45" class="lof-slidecontent" style="width:980px; height:340px;">
    <div class="preload"><div> </div> </div>
  
  <div class="lof-main-outer" style="width:980px; height:340px;">
    <ul class="lof-main-wapper">
      <li>
        <%= image_tag('slides/sms_01.jpg') %>
        <div class="lof-main-item-desc">
          <h3><a target="_parent" title="Ipso Lorem" href="#">Ipso Lorem Sit Amet</a></h3>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since...
            <a class="readmore" href="#"> Leer más </a>
          </p>
        </div>
      </li> 
      <li>
        <%= image_tag('slides/sms_02.jpg') %>
        <div class="lof-main-item-desc">
          <h3><a target="_parent" title="Ipso Lorem" href="#">Ipso Lorem Sit Amet</a></h3>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since...
            <a class="readmore" href="#"> Leer más </a>
          </p>
        </div>
      </li> 
      <li>
        <%= image_tag('slides/sms_03.jpg') %>
        <div class="lof-main-item-desc">
          <h3><a target="_parent" title="Ipso Lorem" href="#">Ipso Lorem Sit Amet</a></h3>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since...
            <a class="readmore" href="#"> Leer más </a>
          </p>
        </div>
      </li> 
    </ul>     
  </div>
  
  <!-- NAVIGATOR -->
  <div class="lof-navigator-wapper">
    <div onclick="return false" href="" class="lof-next"></div>
    <div class="lof-navigator-outer">
      <ul class="lof-navigator">
        <li><%= image_tag('slides/sms_01_thumb.jpg') %></li>
        <li><%= image_tag('slides/sms_02_thumb.jpg') %></li>
        <li><%= image_tag('slides/sms_03_thumb.jpg') %></li>
      </ul>
    </div>
    <div onclick="return false" href="" class="lof-previous"></div>
  </div> 
</div> 
<!-- SLIDESHOW FINAL --> 


<div id="home-columns">
  <div id="home-column-left">
    <h2><%= t(:its_the_best) %></h2>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
  </div>
  <div id="home-column-middle">
    <h2><%= t(:its_the_most_cheaper) %></h2>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
  </div>
  <div id="home-column-right">
    <h2><%= t(:its_free) %></h2>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
  </div>
</div>